# Generated by Django 5.0 on 2025-10-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Page number'),
        ),
    ]
