# Generated by Django 5.0 on 2025-10-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_song_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='negative_page_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Negative page number'),
        ),
        migrations.AlterField(
            model_name='song',
            name='page_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Page number'),
        ),
    ]
