# Generated by Django 5.0 on 2024-04-26 16:55

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Name')),
                ('order', models.IntegerField(unique=True, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SongBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('melody', models.CharField(blank=True, max_length=255, null=True, verbose_name='Melody')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content')),
                ('audio', models.FileField(blank=True, null=True, upload_to='', verbose_name='Audio')),
                ('order', models.IntegerField(blank=True, verbose_name='#')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.category')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='songbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.songbook'),
        ),
    ]
