# Generated by Django 5.0 on 2024-04-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='#'),
        ),
    ]
